name: Frontend Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.2.0'  # Or your desired version

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps  # avoid dependency resolution errors

      - name: Build React App
        run: |
          CI=false npm run build  # disables "treat warnings as errors"

      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SCP
        run: |
          ssh -o StrictHostKeyChecking=no root@68.183.94.76 "rm -rf /var/www/html/yourapp/*"
          scp -r ./build/* root@68.183.94.76:/var/www/html/yourapp/
